const fs = require('fs');
const path = require('path');

// Function to parse simulation logs and extract structured data
function parseSimulationLogs() {
    console.log('🔍 Parsing Smart Suggestions simulation logs...');
    
    // Sample log entries that would be generated by our simulation system
    // In a real scenario, these would come from actual application logs
    const sampleLogs = [
        '🔍 [SuggestionService] Weighting system would have suggested: { description: "initial contribution", keywords: ["initial", "contribution"], suggestedAccount: "Charitable Contributions", confidence: 95, entryType: "CREDIT", reason: "Based on account weighting for \'contribution\' keyword" }',
        '🔍 [SuggestionService] Weighting system would have suggested: { description: "sold products", keywords: ["sold", "products"], suggestedAccount: "Sales Revenue", confidence: 90, entryType: "CREDIT", reason: "Based on account weighting for \'sold\' keyword" }',
        '🔍 [SuggestionService] Weighting system would have suggested: { description: "bought equipment", keywords: ["bought", "equipment"], suggestedAccount: "Equipment Purchase", confidence: 85, entryType: "DEBIT", reason: "Based on account weighting for \'bought\' keyword" }',
        '🔍 [SuggestionService] Weighting system would have suggested: { description: "rent payment", keywords: ["rent", "payment"], suggestedAccount: "Rent Expense", confidence: 88, entryType: "DEBIT", reason: "Based on account weighting for \'rent\' keyword" }',
        '🔍 [SuggestionService] Weighting system would have suggested: { description: "employee salary", keywords: ["employee", "salary"], suggestedAccount: "Payroll Expense", confidence: 92, entryType: "DEBIT", reason: "Based on account weighting for \'salary\' keyword" }',
        '🔍 [SuggestionService] Weighting system would have suggested: { description: "inventory purchase", keywords: ["inventory", "purchase"], suggestedAccount: "Inventory", confidence: 87, entryType: "DEBIT", reason: "Based on account weighting for \'inventory\' keyword" }',
        '🔍 [SuggestionService] Weighting system would have suggested: { description: "utility bill", keywords: ["utility", "bill"], suggestedAccount: "Utilities Expense", confidence: 83, entryType: "DEBIT", reason: "Based on account weighting for \'utility\' keyword" }',
        '🔍 [SuggestionService] Weighting system would have suggested: { description: "loan payment", keywords: ["loan", "payment"], suggestedAccount: "Loan Payable", confidence: 89, entryType: "CREDIT", reason: "Based on account weighting for \'loan\' keyword" }',
        '🔍 [SuggestionService] Weighting system would have suggested: { description: "insurance premium", keywords: ["insurance", "premium"], suggestedAccount: "Insurance Expense", confidence: 86, entryType: "DEBIT", reason: "Based on account weighting for \'insurance\' keyword" }',
        '🔍 [SuggestionService] Weighting system would have suggested: { description: "consulting fee", keywords: ["consulting", "fee"], suggestedAccount: "Professional Services", confidence: 91, entryType: "DEBIT", reason: "Based on account weighting for \'consulting\' keyword" }'
    ];

    const structuredData = [];

    sampleLogs.forEach(logEntry => {
        try {
            // Extract the object part from the log entry
            const startIndex = logEntry.indexOf('{');
            const endIndex = logEntry.lastIndexOf('}');
            
            if (startIndex === -1 || endIndex === -1) {
                console.log(`⚠️ No object found in log entry: ${logEntry}`);
                return;
            }
            
            const objectStr = logEntry.substring(startIndex, endIndex + 1);
            
            // Manually parse the object string to handle the complex format
            const parsed = parseObjectString(objectStr);
            if (parsed) {
                structuredData.push(parsed);
            }
        } catch (error) {
            console.log(`⚠️ Failed to parse log entry: ${logEntry}`);
            console.log(`Error: ${error.message}`);
        }
    });

    return structuredData;
}

// Function to manually parse the object string
function parseObjectString(objectStr) {
    try {
        // Convert the object-like string to proper JSON
        let jsonStr = objectStr
            .replace(/'/g, '"')  // Replace single quotes with double quotes
            .replace(/(\w+):/g, '"$1":')  // Add quotes around property names
            .replace(/,\s*}/g, '}')  // Remove trailing commas
            .replace(/,\s*]/g, ']');  // Remove trailing commas in arrays
        
        // Handle the specific case where we have nested quotes
        jsonStr = jsonStr.replace(/"([^"]*)"([^"]*)"([^"]*)"/g, '"$1$2$3"');
        
        const parsed = JSON.parse(jsonStr);
        return parsed;
    } catch (error) {
        // If JSON parsing fails, try manual extraction
        return extractObjectManually(objectStr);
    }
}

// Function to manually extract object properties
function extractObjectManually(objectStr) {
    const result = {};
    
    // Extract description
    const descMatch = objectStr.match(/description:\s*"([^"]+)"/);
    if (descMatch) result.description = descMatch[1];
    
    // Extract keywords array
    const keywordsMatch = objectStr.match(/keywords:\s*\[([^\]]+)\]/);
    if (keywordsMatch) {
        const keywordsStr = keywordsMatch[1];
        result.keywords = keywordsStr.split(',').map(k => k.trim().replace(/"/g, ''));
    }
    
    // Extract suggestedAccount
    const accountMatch = objectStr.match(/suggestedAccount:\s*"([^"]+)"/);
    if (accountMatch) result.suggestedAccount = accountMatch[1];
    
    // Extract confidence
    const confidenceMatch = objectStr.match(/confidence:\s*(\d+)/);
    if (confidenceMatch) result.confidence = parseInt(confidenceMatch[1]);
    
    // Extract entryType
    const entryTypeMatch = objectStr.match(/entryType:\s*"([^"]+)"/);
    if (entryTypeMatch) result.entryType = entryTypeMatch[1];
    
    // Extract reason
    const reasonMatch = objectStr.match(/reason:\s*"([^"]+)"/);
    if (reasonMatch) result.reason = reasonMatch[1];
    
    return result;
}

// Function to sort data by various criteria
function sortData(data, sortBy = 'confidence') {
    switch (sortBy) {
        case 'confidence':
            return data.sort((a, b) => b.confidence - a.confidence);
        case 'description':
            return data.sort((a, b) => a.description.localeCompare(b.description));
        case 'entryType':
            return data.sort((a, b) => a.entryType.localeCompare(b.entryType));
        case 'keywords':
            return data.sort((a, b) => a.keywords.length - b.keywords.length);
        default:
            return data;
    }
}

// Function to save data to JSON file
function saveToJSON(data, filename = 'diagnostic_suggestions.json') {
    const outputPath = path.join(__dirname, filename);
    fs.writeFileSync(outputPath, JSON.stringify(data, null, 2));
    console.log(`✅ Saved ${data.length} entries to ${outputPath}`);
}

// Function to save data to CSV file
function saveToCSV(data, filename = 'diagnostic_suggestions.csv') {
    const outputPath = path.join(__dirname, filename);
    
    // Create CSV header
    const headers = ['description', 'keywords', 'suggestedAccount', 'confidence', 'entryType', 'reason'];
    const csvHeader = headers.join(',');
    
    // Create CSV rows
    const csvRows = data.map(entry => {
        return headers.map(header => {
            let value = entry[header];
            if (Array.isArray(value)) {
                value = value.join(';');  // Join arrays with semicolon
            }
            // Escape quotes and wrap in quotes if contains comma
            value = value.toString().replace(/"/g, '""');
            if (value.includes(',') || value.includes('"') || value.includes('\n')) {
                value = `"${value}"`;
            }
            return value;
        }).join(',');
    });
    
    const csvContent = [csvHeader, ...csvRows].join('\n');
    fs.writeFileSync(outputPath, csvContent);
    console.log(`✅ Saved ${data.length} entries to ${outputPath}`);
}

// Main execution
function main() {
    try {
        // Parse the simulation logs
        const data = parseSimulationLogs();
        
        if (data.length === 0) {
            console.log('❌ No simulation data found. Make sure the application has been running and generating logs.');
            return;
        }

        console.log(`📊 Found ${data.length} simulation entries`);

        // Sort by confidence (descending) by default
        const sortedData = sortData(data, 'confidence');
        
        // Save to JSON
        saveToJSON(sortedData);
        
        // Save to CSV
        saveToCSV(sortedData);
        
        // Display summary
        console.log('\n📈 Summary:');
        console.log(`Total entries: ${data.length}`);
        console.log(`Average confidence: ${(data.reduce((sum, entry) => sum + entry.confidence, 0) / data.length).toFixed(1)}%`);
        console.log(`Entry types: ${[...new Set(data.map(entry => entry.entryType))].join(', ')}`);
        console.log(`Unique accounts: ${new Set(data.map(entry => entry.suggestedAccount)).size}`);
        
        // Show top 3 suggestions by confidence
        console.log('\n🏆 Top 3 suggestions by confidence:');
        sortedData.slice(0, 3).forEach((entry, index) => {
            console.log(`${index + 1}. "${entry.description}" → ${entry.suggestedAccount} (${entry.confidence}%)`);
        });

    } catch (error) {
        console.error('❌ Error parsing simulation logs:', error.message);
    }
}

// Run the script
main(); 