export const CHART_OF_ACCOUNTS = {
  assets: {
    cash: 'Cash & Checking',
    savings: 'Savings',
    accounts_receivable: 'Accounts Receivable',
    inventory: 'Inventory',
    prepaid_expenses: 'Prepaid Expenses',
    vehicles: 'Vehicles',
    equipment: 'Equipment',
    furniture: 'Furniture',
    leasehold_improvements: 'Leasehold Improvements',
    deposits: 'Deposits',
    intangible_assets: 'Intangible Assets',
  },
  liabilities: {
    accounts_payable: 'Accounts Payable',
    credit_card: 'Credit Card Payable',
    sales_tax: 'Sales Tax Payable',
    payroll: 'Payroll Liabilities',
    vehicle_loans: 'Vehicle Loans',
    sba_loan: 'SBA Loan',
    mortgage: 'Mortgage Payable',
  },
  equity: {
    owners_equity: "Owner's Equity",
    owners_contributions: "Owner's Contributions",
    owners_draws: "Owner's Draws",
    retained_earnings: 'Retained Earnings',
  },
  income: {
    service_revenue: 'Service Revenue',
    product_sales: 'Product Sales',
    interest_income: 'Interest Income',
    rental_income: 'Rental Income',
    consulting_revenue: 'Consulting Revenue',
    commission_income: 'Commission Income',
    other_income: 'Other Income',
  },
  cogs: {
    materials: 'Materials & Supplies',
    inventory_cost: 'Cost of Inventory Sold',
    subcontractor: 'Subcontractor Labor',
    shipping: 'Shipping & Delivery',
  },
  expenses: {
    advertising: 'Advertising & Marketing',
    office_supplies: 'Office Supplies',
    utilities: 'Utilities',
    insurance: 'Insurance',
    fuel: 'Fuel',
    meals: 'Meals & Entertainment',
    professional_services: 'Professional Services',
    repairs: 'Repairs & Maintenance',
    rent: 'Rent',
    software: 'Software Subscriptions',
    wages: 'Wages & Payroll',
    taxes: 'Taxes & Licenses',
    travel: 'Travel',
    bank_fees: 'Bank Fees',
    telephone: 'Telephone',
    internet: 'Internet',
    training: 'Training & Development',
    cleaning: 'Cleaning Services',
    security: 'Security Services',
    landscaping: 'Landscaping Services',
    parking: 'Parking',
    postage: 'Postage & Delivery',
    printing: 'Printing & Reproduction',
    storage: 'Storage',
    uniforms: 'Uniforms & Work Clothes',
    waste: 'Waste Disposal',
    water: 'Water',
    workers_comp: 'Workers Compensation',
    other: 'Other Expenses',
  },
}; 